---
title: "Art Attempts"
author: "Ellen Graham"
date: "1/21/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(sf)
library(readr)
library(viridis)
library(ggmap)
library(rnaturalearth)
library(lubridate)
library(purrr)
library(tidyr)

```


Load in the data
```{r}

date_time_data <- readr::read_csv("Miss_explore/clean_data/date_time_data.csv")
clean_legs <- st_read("Miss_explore/clean_data/clean_legs/clean_data_geom.shp") %>% 
  mutate(date_time = date_time_data$date_time)

tiny_legs = clean_legs[seq(1, nrow(clean_legs), 10), ]

coords <- st_coordinates(clean_legs)



miss_basin <- st_read("Miss_explore/clean_data/miss_basin/Miss_RiverBasin.shp") %>% 
  st_transform(crs = 4326)

river_10 <- st_as_sf(ne_download(scale = 10, type = 'rivers_lake_centerlines', category = 'physical'))


miss_basin_rivers_10 <- st_intersection(miss_basin, river_10)
```

```{r}
chunk_1_interval <- interval(ymd_hms("2019-08-29 00:00:00"),
                             ymd_hms("2019-09-03 23:59:59"))

chunk_2_interval <- interval(ymd_hms("2019-09-24 00:00:00"),
                             ymd_hms("2019-09-26 23:59:59"))

chunk_3_interval <- interval(ymd_hms("2019-10-08 00:00:00"),
                             ymd_hms("2019-10-12 23:59:59"))

chunk_4_interval <- interval(ymd_hms("2019-10-13 00:00:00"),
                             ymd_hms("2019-10-18 23:59:59"))

chunk_5_interval <- interval(ymd_hms("2019-10-31 00:00:00"),
                             ymd_hms("2019-11-22 23:59:59"))

chunk_intervals <- list(chunk_1_interval,
                        chunk_2_interval,
                        chunk_3_interval,
                        chunk_4_interval,
                        chunk_5_interval)

chunk_num <- map(chunk_intervals, function(b, a){a %within% b}, clean_legs$date_time) %>% 
  pmap_int(function(a, b, c, d, e) {
      chunk_num <- which(c(a, b, c, d, e))
      
      ifelse(length(chunk_num) == 0, NA, chunk_num)
    })
clean_legs_non_geom <- st_drop_geometry(clean_legs) %>% 
  select(-date_tm) %>% 
  bind_cols(as.data.frame(coords)) %>% 
  rename(lat = "Y", lon = "X") %>% 
  mutate(chunk = chunk_num) %>% 
  filter(!is.na(chunk)) %>% 
  mutate(index = index + ((chunk-1)*50))


(first_per_chunk <- clean_legs_non_geom[seq(1, nrow(clean_legs), 30), ] %>% 
  mutate(index = 1:n() + 50*(chunk-1)) %>% 
  group_by(chunk) %>% 
  summarise(index = first(index), lat = first(lat), lon = first(lon)))

(last_per_chunk <- clean_legs_non_geom[seq(1, nrow(clean_legs), 30), ] %>% 
  mutate(index = 1:n() + 50*(chunk-1)) %>% 
  group_by(chunk) %>% 
  summarise(index = last(index), lat = last(lat), lon = last(lon)))

```


Start Visualizing
```{r, fig.width=4, fig.height=10, dev = "svg"}

map_left_edge <- -98

gradient_right_edge <- -96
gradient_top_edge <- 48.16291
gradient_bottom_edge <- 28.92833
first_last_chunk <- bind_rows(first_per_chunk, last_per_chunk)

lat_to_y_mercator <- function(lat) {
  log(tan(lat*pi/180) + 1/cos(lat*pi/180))
}

grad_top_y <- lat_to_y_mercator(gradient_top_edge)
grad_bottom_y <- lat_to_y_mercator(gradient_bottom_edge)


calc_appropriate_lat <- function(index_ratio) {
  y = (grad_top_y - grad_bottom_y)*index_ratio + grad_bottom_y
  atan(sinh(y)) *180/pi
}




first_last_chunk <- first_last_chunk %>% 
  mutate(index_ratio = 1-(index-min(index))/(max(index)-1)) %>% 
  mutate(grad_lat = calc_appropriate_lat(index_ratio)) %>% 
  mutate(grad_lon = gradient_right_edge) %>% 
  rename(river_lat = lat, river_lon = lon) #%>% 
#  select(-index_ratio)

first_last_chunk[c(1,6),c(3,4)] <- first_last_chunk[c(6,1),c(3,4)]


line_data <- first_last_chunk %>% 
  pivot_longer(cols = river_lat:grad_lon, 
               names_to = c("end", ".value"),
               names_pattern = "(grad|river)_(lat|lon)") %>% 
  group_by(index) %>% 
  group_split() %>% 
  map(select, lon, lat) %>% 
  map(as.matrix) %>% 
  map(st_linestring, dim = "XY") %>% 
  st_as_sfc(crs = 4326) %>% 
  st_as_sf() %>% 
  mutate(chunk = as.character(rep(1:5, each = 2)))

miss_cities <- tibble(name = c("Memphis", "Minneapolis", "New Orleans", "St. Louis", "Baton Rouge"),
                      lat = c(35.1495, 44.9778, 29.9511, 38.6270, 30.4515),
                      lon = c(-90.0490, -93.2650, -90.0715, -90.1994, -91.1871)) %>% 
  st_as_sf(coords = c("lon", "lat"), remove = FALSE, crs = 4326)

us_states <- st_as_sf(ne_states(country = "United States of America"))


(map <- ggplot() +
  geom_sf(data = us_states, fill= "#F1F2F4", color = "white") +
  geom_sf(data = miss_basin_rivers_10, color = "#b1d3de") +
  geom_sf(data = filter(miss_basin_rivers_10, name %in% c("Mississippi")), size = 1.5, color = "#85c9de") +
  geom_sf(data = miss_cities, size = 2) +
  geom_text(data = miss_cities, 
            aes(x = lon, y = lat, label = name),
            hjust = 0, 
            nudge_x = 0.3, nudge_y = 0.3,
            fontface = "italic",
            color = "grey22",
            size = 4) +
  geom_sf(data = line_data, color = "gray22", show.legend = FALSE) +
  geom_sf(data = clean_legs[seq(1, nrow(clean_legs), 30), ], aes(color = heading), alpha = 0.2, size = 1.5, show.legend = FALSE) +
  scale_color_viridis(option = "D") +
  coord_sf(datum = NA, 
           xlim = c(map_left_edge, -87.5),
           ylim = c(28.85423, 49.7391)) +
  theme_void())

(gradient <- clean_legs_non_geom[seq(1, nrow(clean_legs), 30), ] %>% 
  mutate(index = 1:n() + 50*(chunk-1)) %>% 
  ggplot() +
  geom_tile(aes(x = 0, y = -index, fill = heading), width = 1, height = 11, alpha = 0.3) +
  scale_fill_viridis(option = "D", na.value = "gray85") +
  theme_void() +
  theme(legend.position = "none") +
  coord_cartesian(ylim = -c(1, 1042),
                  xlim = c(-0.5, 0.5),
                  expand = FALSE))

(final_map <- map +
  annotation_custom(ggplotGrob(gradient), 
                    xmin = map_left_edge +1,
                    xmax = gradient_right_edge,
                    ymin = gradient_bottom_edge,
                    ymax = gradient_top_edge))


ggsave("test_map.svg", 
       plot = final_map, 
       device = "svg",
       width = 4,
       height = 10)
```




